name: ble_scanner_app
description: "App BLE to scan BLE near devices"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter_blue_plus: ^1.16.2
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_blue:
  get: ^4.6.5
  permission_handler:
  fl_chart: ^0.68.0
  path_provider: ^2.0.14
  path_provider_android: ^2.0.11
  csv: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

